import type { Metadata } from "next";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { JsonLd } from "@/components/JsonLd";

const SITE_URL = "https://homecrew.com";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms that govern your use of MyHomeQuote, our AI assistant Nora, and our service that connects homeowners with independent licensed contractors.",
  alternates: { canonical: "/terms" },
};

const TERMS_SCHEMA = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: SITE_URL },
    {
      "@type": "ListItem",
      position: 2,
      name: "Terms of Service",
      item: `${SITE_URL}/terms`,
    },
  ],
};

// Bracketed items are placeholders to complete before publishing:
// [COMPANY LEGAL NAME], [EFFECTIVE DATE], [legal@yourdomain.com], [MAILING ADDRESS], [STATE].
type Block = string | { sub: string } | { list: string[] };
interface Section {
  heading: string;
  blocks: Block[];
}

const SECTIONS: Section[] = [
  {
    heading: "1. Agreement to these Terms",
    blocks: [
      'These Terms of Service ("Terms") are a binding agreement between you and [COMPANY LEGAL NAME], doing business as MyHomeQuote ("MyHomeQuote," "we," "us," or "our"), and govern your access to and use of our website, our AI assistant Nora, and our related services (together, the "Services").',
      "By accessing or using the Services, you agree to these Terms and to our Privacy Policy. If you do not agree, do not use the Services.",
    ],
  },
  {
    heading: "2. Eligibility",
    blocks: [
      "You must be at least 18 years old and a resident of the United States to use the Services. By using the Services, you represent that you meet these requirements and that the information you provide is accurate and belongs to you.",
    ],
  },
  {
    heading: "3. What MyHomeQuote is (and is not)",
    blocks: [
      "MyHomeQuote is a lead-generation and matching service. We help you describe your home improvement project and connect you with independent, third-party licensed contractors and service professionals (each, a \"Pro\") who may contact you to discuss your project and provide a consultation or quote.",
      "MyHomeQuote is not a contractor, home improvement company, or licensed professional. We do not perform any home improvement work, do not provide quotes or pricing ourselves, and are not a party to any agreement you enter into with a Pro. Any work, quote, contract, warranty, or payment is solely between you and the Pro.",
    ],
  },
  {
    heading: "4. Nora, our AI assistant",
    blocks: [
      "Nora is an automated AI assistant, not a human, and is provided to help you describe your project and arrange a consultation. Nora's responses are generated by artificial intelligence, may be inaccurate or incomplete, and do not constitute professional, legal, financial, or construction advice.",
      "Do not rely on Nora for emergencies. For water leaks, gas, electrical hazards, or any situation that may pose a risk to safety, contact a licensed professional or emergency services immediately.",
      "Your chat messages are processed by third-party AI providers as described in our Privacy Policy. Do not share information through the chat that you do not want processed by an AI provider.",
    ],
  },
  {
    heading: "5. Independent contractors; no endorsement",
    blocks: [
      "Pros are independent third parties. We do not employ, control, supervise, or direct Pros, and we do not guarantee, endorse, or warrant any Pro, their licensing or insurance, their availability, or the quality, safety, timeliness, legality, or price of any work they perform.",
      "You are responsible for evaluating and selecting any Pro, verifying their licensing, insurance, and qualifications, and negotiating and agreeing to the terms of any work directly with them. We encourage you to obtain multiple quotes and a written contract before any work begins.",
    ],
  },
  {
    heading: "6. Consultations and quotes",
    blocks: [
      "We do not guarantee that a Pro will contact you, that a consultation or quote will be provided, or that any particular price, timeline, availability, or outcome will result. Any estimates, timelines, or figures shared through the Services (including anything shown in guides or discussed with Nora) are general information only and are not offers, quotes, or guarantees.",
    ],
  },
  {
    heading: "7. Communications consent",
    blocks: [
      "By submitting your contact information, you agree that MyHomeQuote and the Pros we match you with may contact you by phone call, text message (SMS), and email regarding your request, including through automated technology. Consent is not a condition of any purchase. Message and data rates may apply, and message frequency varies. You can reply STOP to opt out of text messages and HELP for help. See our Privacy Policy for more detail.",
    ],
  },
  {
    heading: "8. Your responsibilities and acceptable use",
    blocks: [
      "You agree to provide accurate, current, and complete information and to use the Services only for lawful purposes. You agree not to:",
      {
        list: [
          "Submit information that is false, misleading, or not your own, or request services on behalf of someone else without their permission;",
          "Use the Services in violation of any law or regulation;",
          "Interfere with, disrupt, or attempt to gain unauthorized access to the Services or related systems;",
          "Scrape, crawl, harvest, or use automated means to access or collect data from the Services, except as expressly permitted;",
          "Upload or transmit viruses, malware, or other harmful code; or",
          "Reverse engineer, resell, or make commercial use of the Services without our permission.",
        ],
      },
    ],
  },
  {
    heading: "9. Content you provide",
    blocks: [
      "You retain ownership of the information and content you submit to the Services (\"Your Content\"). You grant MyHomeQuote a non-exclusive, worldwide, royalty-free license to use, host, store, reproduce, and process Your Content as needed to operate and improve the Services and to share it with Pros so they can contact you, as described in our Privacy Policy. You represent that you have the rights necessary to grant this license.",
    ],
  },
  {
    heading: "10. Intellectual property",
    blocks: [
      "The Services, including our website, content, branding, logos, and the name MyHomeQuote, are owned by us or our licensors and are protected by intellectual property laws. We grant you a limited, non-exclusive, non-transferable, revocable license to access and use the Services for their intended purpose. You may not use our trademarks without our prior written permission.",
    ],
  },
  {
    heading: "11. Third-party links and services",
    blocks: [
      "The Services may contain links to, or rely on, third-party websites and services (including those of Pros and technology providers) that we do not control. We are not responsible for the content, products, services, or practices of any third party, and your use of them is at your own risk and subject to their terms.",
    ],
  },
  {
    heading: "12. Disclaimers",
    blocks: [
      'THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE, OR THAT ANY INFORMATION (INCLUDING AI-GENERATED RESPONSES) WILL BE ACCURATE OR RELIABLE.',
      "WE MAKE NO WARRANTY REGARDING ANY PRO OR ANY WORK, GOODS, OR SERVICES THEY PROVIDE. ANY DEALINGS WITH A PRO ARE SOLELY BETWEEN YOU AND THE PRO.",
    ],
  },
  {
    heading: "13. Limitation of liability",
    blocks: [
      "TO THE MAXIMUM EXTENT PERMITTED BY LAW, MYHOMEQUOTE AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, DATA, OR GOODWILL, ARISING FROM OR RELATED TO YOUR USE OF THE SERVICES OR ANY DEALINGS WITH A PRO, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.",
      "TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICES WILL NOT EXCEED ONE HUNDRED U.S. DOLLARS ($100). SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS, SO SOME OF THESE MAY NOT APPLY TO YOU.",
    ],
  },
  {
    heading: "14. Indemnification",
    blocks: [
      "You agree to indemnify and hold harmless MyHomeQuote and its officers, directors, employees, and agents from any claims, liabilities, damages, losses, and expenses (including reasonable attorneys' fees) arising out of or related to your use of the Services, your violation of these Terms, or your dealings with any Pro.",
    ],
  },
  {
    heading: "15. Governing law and dispute resolution",
    blocks: [
      "These Terms are governed by the laws of the State of [STATE], without regard to its conflict-of-laws rules.",
      "Please read this section carefully. Except where prohibited by law, you and MyHomeQuote agree to resolve any dispute arising out of or relating to these Terms or the Services through final and binding individual arbitration, rather than in court, and to waive any right to a jury trial or to participate in a class action. Details of the arbitration process, including the arbitration provider and any right to opt out, are set out here: [DESCRIBE ARBITRATION PROCESS / PROVIDER / OPT-OUT]. Either party may bring an individual claim in small-claims court where eligible.",
    ],
  },
  {
    heading: "16. Changes to the Services and these Terms",
    blocks: [
      "We may modify, suspend, or discontinue the Services, in whole or in part, at any time. We may also update these Terms from time to time. When we do, we will revise the date below and, if the changes are material, provide additional notice. Your continued use of the Services after an update means you accept the revised Terms.",
    ],
  },
  {
    heading: "17. Termination",
    blocks: [
      "We may suspend or terminate your access to the Services at any time, with or without notice, if we believe you have violated these Terms or to protect the Services or others. Sections that by their nature should survive termination will survive.",
    ],
  },
  {
    heading: "18. Miscellaneous",
    blocks: [
      "These Terms, together with our Privacy Policy, are the entire agreement between you and MyHomeQuote regarding the Services. If any provision is found unenforceable, the remaining provisions will remain in effect. Our failure to enforce any provision is not a waiver. You may not assign these Terms without our consent; we may assign them in connection with a merger, acquisition, or sale of assets.",
    ],
  },
  {
    heading: "19. Contact us",
    blocks: [
      "If you have questions about these Terms, contact us at:",
      "[COMPANY LEGAL NAME] (MyHomeQuote), [MAILING ADDRESS], [legal@yourdomain.com].",
    ],
  },
];

function renderBlock(block: Block, i: number) {
  if (typeof block === "string") {
    return (
      <p
        key={i}
        className="m-0 text-[15.5px] font-normal leading-[1.75] text-ink/[.78]"
      >
        {block}
      </p>
    );
  }
  if ("sub" in block) {
    return (
      <h3
        key={i}
        className="m-0 mt-2 text-[16px] font-semibold leading-[1.3] text-ink"
      >
        {block.sub}
      </h3>
    );
  }
  return (
    <ul key={i} className="m-0 flex list-disc flex-col gap-2 pl-5">
      {block.list.map((li, j) => (
        <li
          key={j}
          className="text-[15.5px] font-normal leading-[1.7] text-ink/[.78]"
        >
          {li}
        </li>
      ))}
    </ul>
  );
}

export default function TermsPage() {
  return (
    <main className="w-full bg-white">
      <JsonLd data={TERMS_SCHEMA} />
      <Header />

      <section className="px-5 py-12 sm:px-8 sm:py-16 lg:px-12">
        <div className="mx-auto flex w-full max-w-[760px] flex-col gap-10">
          <div className="flex flex-col gap-[14px]">
            <div className="font-mono text-[10.5px] font-medium uppercase leading-none tracking-[.14em] text-accent-link">
              Legal
            </div>
            <h1 className="balance m-0 text-[32px] font-extrabold leading-[1.1] tracking-tighter2 text-ink sm:text-[42px]">
              Terms of Service
            </h1>
            <p className="m-0 text-[13px] font-medium leading-none text-ink/45">
              Last updated: [EFFECTIVE DATE]
            </p>
          </div>

          {SECTIONS.map((section) => (
            <div key={section.heading} className="flex flex-col gap-3">
              <h2 className="m-0 text-[20px] font-bold leading-[1.25] tracking-[-.02em] text-ink sm:text-[22px]">
                {section.heading}
              </h2>
              {section.blocks.map(renderBlock)}
            </div>
          ))}
        </div>
      </section>

      <Footer />
    </main>
  );
}
